name: Quality checks

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  audit:
    uses: ./.github/workflows/reusable-quality.yml
    with:
      command: pnpm audit --prod

  format:
    uses: ./.github/workflows/reusable-quality.yml
    with:
      command: pnpm format:check

  lint:
    uses: ./.github/workflows/reusable-quality.yml
    with:
      command: pnpm lint

  test:
    uses: ./.github/workflows/reusable-quality.yml
    with:
      command: pnpm test:ci
